// <auto-generated/>
using Deterministic.GameFramework.DAR;
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.Reactive;
using Template.Shared.Components;
using Deterministic.GameFramework.TwoD;
using R3;

namespace Template.Godot.Visuals;

public partial class Bush2ViewModel : EntityViewModel
{
    public Bush2DefinitionModel Bush2 { get; }

    public Bush2ViewModel(Context context) : base(context)
    {
        Bush2 = new Bush2DefinitionModel(ReactiveSystem.Instance, context);
        Disposables.Add(Bush2);

        OnInitialize(context);
        OnCreated();
    }

    /// <summary>Called after all generated properties are initialized. Use to set up custom reactive bindings.</summary>
    partial void OnInitialize(Context context);
    partial void OnCreated();
}
