// <auto-generated/>
using Deterministic.GameFramework.DAR;
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.Reactive;
using Template.Shared.Components;
using Deterministic.GameFramework.TwoD;
using R3;

namespace Template.Godot.Visuals;

public partial class Bush1ViewModel : EntityViewModel
{
    public Bush1DefinitionModel Bush1 { get; }

    public Bush1ViewModel(Context context) : base(context)
    {
        Bush1 = new Bush1DefinitionModel(ReactiveSystem.Instance, context);
        Disposables.Add(Bush1);

        OnInitialize(context);
        OnCreated();
    }

    /// <summary>Called after all generated properties are initialized. Use to set up custom reactive bindings.</summary>
    partial void OnInitialize(Context context);
    partial void OnCreated();
}
