// <auto-generated/>
using System;
using System.Collections.Generic;
using Godot;
using R3;
using ObservableCollections;
using Template.Godot.Core;
using Template.Shared.Components;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using DTransform2D = Deterministic.GameFramework.TwoD.Transform2D;
using GVector3 = Godot.Vector3;

namespace Template.Godot.Visuals;

public partial class Bush1View : Node3D
{
    [Export] public PackedScene Prefab;

    private readonly CompositeDisposable _disposables = new();
    private readonly Dictionary<Bush1ViewModel, Node3D> _spawnedEntities = new();
    [Export] public float DespawnDelay = 0f;

    private bool _registered;

    public override void _Ready()
    {
        if (GameManager.Instance != null && GameManager.Instance.IsGameRunning)
        {
            Register();
            SetProcess(false);
        }
    }

    public override void _Process(double delta)
    {
        if (_registered || GameManager.Instance == null || !GameManager.Instance.IsGameRunning) return;
        SetProcess(false);
        Register();
    }

    private void Register()
    {
        _registered = true;
        var client = GameManager.Instance.GameClient;
        var list = client.Reactive.ObservableList<PropComponent, DTransform2D, Bush1ViewModel>(
            ctx => new Bush1ViewModel(ctx),
            _disposables
        );

        list.ObserveAdd().Subscribe(e => Callable.From(() => OnAdded(e.Value)).CallDeferred()).AddTo(_disposables);
        list.ObserveRemove().Subscribe(e => Callable.From(() => OnRemoved(e.Value)).CallDeferred()).AddTo(_disposables);
        list.ObserveReset().Subscribe(_ => Callable.From(OnReset).CallDeferred()).AddTo(_disposables);
        // Spawn existing entities (deduped by ContainsKey in OnAdded)
        foreach (var vm in list) OnAdded(vm);
    }

    private void OnAdded(Bush1ViewModel vm)
    {
        if (_spawnedEntities.ContainsKey(vm)) return;

        var visualNode = Prefab?.Instantiate<Node3D>() ?? CreateFallbackVisual();

        AddChild(visualNode);
        _spawnedEntities[vm] = visualNode;
        var pos = vm.Transform.Position.CurrentValue;
        visualNode.SetDeferred("position", new GVector3((float)pos.X, 0f, (float)pos.Y));

        OnSpawned(vm, visualNode);
    }

    private void OnRemoved(Bush1ViewModel vm)
    {
        if (_spawnedEntities.TryGetValue(vm, out var node))
        {
            _spawnedEntities.Remove(vm);
            if (IsInstanceValid(node))
            {
                OnDespawned(vm, node);
                if (DespawnDelay > 0f)
                {
                    GetTree().CreateTimer(DespawnDelay).Timeout += () => { if (IsInstanceValid(node)) node.QueueFree(); };
                }
                else
                {
                    node.QueueFree();
                }
            }
        }
        vm.Dispose();
    }

    private void OnReset()
    {
        foreach (var vm in new List<Bush1ViewModel>(_spawnedEntities.Keys))
            OnRemoved(vm);
    }

    private static Node3D CreateFallbackVisual()
    {
        var node = new Node3D();
        var meshInstance = new MeshInstance3D();
        var mesh = new CylinderMesh { TopRadius = 0.5f, BottomRadius = 0.5f, Height = 0.1f };
        mesh.Material = new StandardMaterial3D { AlbedoColor = Colors.White };
        meshInstance.Mesh = mesh;
        node.AddChild(meshInstance);
        return node;
    }

    /// <summary>Called after entity visual is spawned and positioned. Add custom bindings here.</summary>
    partial void OnSpawned(Bush1ViewModel vm, Node3D visualNode);

    /// <summary>Called when entity is being removed. Play disappear animations here. Set DespawnDelay in the editor to defer QueueFree.</summary>
    partial void OnDespawned(Bush1ViewModel vm, Node3D visualNode);

    public override void _ExitTree()
    {
        _disposables.Dispose();
        foreach (var vm in _spawnedEntities.Keys) vm.Dispose();
        _spawnedEntities.Clear();
    }
}
