// <auto-generated/>
using System;
using System.Collections.Generic;
using Godot;
using R3;
using ObservableCollections;
using Template.Godot.Core;
using Template.Shared.Components;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using DTransform2D = Deterministic.GameFramework.TwoD.Transform2D;
using GVector3 = Godot.Vector3;

namespace Template.Godot.Visuals;

public partial class LoveHouseView : Node3D
{
    [Export] public PackedScene Prefab;

    private readonly CompositeDisposable _disposables = new();
    private readonly Dictionary<LoveHouseViewModel, Node3D> _spawnedEntities = new();

    private bool _registered;

    public override void _Ready()
    {
        if (GameManager.Instance != null && GameManager.Instance.IsGameRunning)
        {
            Register();
            SetProcess(false);
        }
    }

    public override void _Process(double delta)
    {
        if (_registered || GameManager.Instance == null || !GameManager.Instance.IsGameRunning) return;
        SetProcess(false);
        Register();
    }

    private void Register()
    {
        _registered = true;
        var client = GameManager.Instance.GameClient;
        var list = client.Reactive.ObservableList<LoveHouseComponent, DTransform2D, LoveHouseViewModel>(
            ctx => new LoveHouseViewModel(ctx),
            _disposables
        );

        list.ObserveAdd().Subscribe(e => Callable.From(() => OnAdded(e.Value)).CallDeferred()).AddTo(_disposables);
        list.ObserveRemove().Subscribe(e => Callable.From(() => OnRemoved(e.Value)).CallDeferred()).AddTo(_disposables);
        list.ObserveReset().Subscribe(_ => Callable.From(OnReset).CallDeferred()).AddTo(_disposables);
        // Spawn existing entities (deduped by ContainsKey in OnAdded)
        foreach (var vm in list) OnAdded(vm);
    }

    private void OnAdded(LoveHouseViewModel vm)
    {
        if (_spawnedEntities.ContainsKey(vm)) return;

        var visualNode = Prefab?.Instantiate<Node3D>() ?? CreateFallbackVisual();

        AddChild(visualNode);
        _spawnedEntities[vm] = visualNode;
        var pos = vm.Transform.Position.CurrentValue;
        visualNode.SetDeferred("position", new GVector3((float)pos.X, 0f, (float)pos.Y));

        OnSpawned(vm, visualNode);
    }

    private void OnRemoved(LoveHouseViewModel vm)
    {
        if (_spawnedEntities.TryGetValue(vm, out var node))
        {
            if (IsInstanceValid(node)) { node.Visible = false; node.QueueFree(); }
            _spawnedEntities.Remove(vm);
        }
    }

    private void OnReset()
    {
        foreach (var vm in new List<LoveHouseViewModel>(_spawnedEntities.Keys))
            OnRemoved(vm);
    }

    private static Node3D CreateFallbackVisual()
    {
        var node = new Node3D();
        var meshInstance = new MeshInstance3D();
        var mesh = new CylinderMesh { TopRadius = 0.5f, BottomRadius = 0.5f, Height = 0.1f };
        mesh.Material = new StandardMaterial3D { AlbedoColor = Colors.White };
        meshInstance.Mesh = mesh;
        node.AddChild(meshInstance);
        return node;
    }

    /// <summary>Called after entity visual is spawned and positioned. Add custom bindings here.</summary>
    partial void OnSpawned(LoveHouseViewModel vm, Node3D visualNode);

    public override void _ExitTree()
    {
        _disposables.Dispose();
        _spawnedEntities.Clear();
    }
}
