// <auto-generated/>
using Deterministic.GameFramework.DAR;
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.Reactive;
using Template.Shared.Components;
using Deterministic.GameFramework.TwoD;
using R3;

namespace Template.Godot.Visuals;

public partial class SellPointSignViewModel : EntityViewModel
{
    public SellPointSignDefinitionModel SellPointSign { get; }

    public SellPointSignViewModel(Context context) : base(context)
    {
        SellPointSign = new SellPointSignDefinitionModel(ReactiveSystem.Instance, context);
        Disposables.Add(SellPointSign);

        OnInitialize(context);
        OnCreated();
    }

    /// <summary>Called after all generated properties are initialized. Use to set up custom reactive bindings.</summary>
    partial void OnInitialize(Context context);
    partial void OnCreated();
}
