// <auto-generated/>
using Deterministic.GameFramework.DAR;
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.Reactive;
using Template.Shared.Components;
using Deterministic.GameFramework.TwoD;
using R3;

namespace Template.Godot.Visuals;

public partial class WallViewModel : EntityViewModel
{
    public WallDefinitionModel Wall { get; }

    public WallViewModel(Context context) : base(context)
    {
        Wall = new WallDefinitionModel(ReactiveSystem.Instance, context);
        Disposables.Add(Wall);

        OnInitialize(context);
        OnCreated();
    }

    /// <summary>Called after all generated properties are initialized. Use to set up custom reactive bindings.</summary>
    partial void OnInitialize(Context context);
    partial void OnCreated();
}
