// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class Area2DNode : Node
{
    [Export] public uint CollisionLayer;
    [Export] public uint CollisionMask;
    [Export] public bool Monitoring;
    [Export] public bool Monitorable;
    [Export] public bool HasOverlappingBodies;
    [Export] public byte EnteredMask;
    [Export] public byte ExitedMask;
}
