// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class CaughtComponentNode : Node
{
    [Export] public int TicksRemaining;
    [Export] public int TotalTicks;
    [Export] public float CowOffsetX;
    [Export] public float CowOffsetY;
}
