// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class CharacterBody2DNode : Node
{
    [Export] public Vector2 Velocity;
    [Export] public Vector2 UpDirection;
    [Export] public float FloorSnapLength;
    [Export] public float WallMinSlideAngle;
    [Export] public float FloorMaxAngle;
    [Export] public bool SlideOnCeiling;
    [Export] public int MaxSlides;
    [Export] public bool FloorConstantSpeed;
    [Export] public uint CollisionLayer;
    [Export] public uint CollisionMask;
    [Export] public Vector2 RealVelocity;
}
