// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class CollisionShape2DNode : Node
{
    [Export] public Vector2 Position;
    [Export] public float Rotation;
    [Export] public bool Disabled;
    [Export] public bool OneWayCollision;
}
