// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class CooldownComponentNode : Node
{
    [Export] public int MaxTicks;
    [Export] public int TicksRemaining;
    [Export] public int Unit;
}
