// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class CowComponentNode : Node
{
    [Export] public int Exhaust;
    [Export] public int MaxExhaust;
    [Export] public bool IsMilking;
    [Export] public Vector2 SpawnPosition;
    [Export] public int PreferredFood;
    [Export] public int SecondaryPreferredFood;
    [Export] public int SelectedFood;
    [Export] public int DiscoveredFoodMask;
    [Export] public int FedGrassCount;
    [Export] public int FedCarrotCount;
    [Export] public int FedAppleCount;
    [Export] public int FedMushroomCount;
    [Export] public bool IsDepressed;
    [Export] public int DepressionTicksRemaining;
    [Export] public bool LoveConfessed;
    [Export] public int PetCount;
    [Export] public int MilkClickCounter;
    [Export] public int Horny;
    [Export] public int MaxHorny;
    [Export] public bool IsExhausted;
    [Export] public bool IsAttacking;
    [Export] public bool IsWanderer;
    [Export] public int HornyIconState;
    [Export] public bool IsLoveTarget;
    [Export] public bool ShowLoveNeedIcon;
    [Export] public bool IsHornyAlerting;
}
