// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

public partial class CowComponentNode : Node
{
    [Export] public int Exhaust;
    [Export] public int MaxExhaust;
    [Export] public bool IsMilking;
}
