// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class CowJumpComponentNode : Node
{
    [Export] public int WindupTicksLeft;
    [Export] public int LeapTicksLeft;
    [Export] public int LeapDurationTicks;
}
