// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class FinalStructureComponentNode : Node
{
    [Export] public int CurrentCoins;
    [Export] public int Threshold;
}
