// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

public partial class GlobalResourcesComponentNode : Node
{
    [Export] public int Grass;
    [Export] public int Milk;
    [Export] public int Coins;
}
