// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class GlobalResourcesComponentNode : Node
{
    [Export] public int Grass;
    [Export] public int Carrot;
    [Export] public int Apple;
    [Export] public int Mushroom;
    [Export] public int Milk;
    [Export] public int CarrotMilkshake;
    [Export] public int VitaminMix;
    [Export] public int PurplePotion;
    [Export] public int Coins;
    [Export] public int TotalBreedCount;
    [Export] public int SpawnedSpecials;
    [Export] public int HelpersEnabled;
    [Export] public int LastFarmGX;
    [Export] public int LastFarmGY;
    [Export] public int HelpersSpawned;
    [Export] public int NextLoveBreedCount;
}
