// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class GrassComponentNode : Node
{
    [Export] public int Durability;
    [Export] public int MaxDurability;
}
