// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class HelperPetComponentNode : Node
{
    [Export] public int HelperType;
    [Export] public int State;
    [Export] public int IdleSpawnX;
    [Export] public int IdleSpawnY;
}
