// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class HelperComponentNode : Node
{
    [Export] public int Type;
    [Export] public int State;
    [Export] public int WorkTimer;
    [Export] public int WorkDuration;
    [Export] public int BagGrass;
    [Export] public int BagCarrot;
    [Export] public int BagApple;
    [Export] public int BagMushroom;
    [Export] public int BagMilk;
    [Export] public int BagCarrotMilkshake;
    [Export] public int BagVitaminMix;
    [Export] public int BagPurplePotion;
    [Export] public int BagCoins;
    [Export] public int BagCapacity;
    [Export] public int WantedFoodType;
}
