// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class LoveHouseComponentNode : Node
{
    [Export] public int BreedProgress;
    [Export] public int BreedCost;
    [Export] public int SameTierBreedCount;
}
