// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class MetricsComponentNode : Node
{
    [Export] public int ElapsedTicks;
    [Export] public int CumFood;
    [Export] public int CumMilk;
    [Export] public int CumCoins;
    [Export] public int PeakCoins;
    [Export] public int PeakFood;
    [Export] public int PeakMilk;
    [Export] public int PeakCows;
    [Export] public int PeakHouses;
    [Export] public int FoodZeroTicks;
    [Export] public int MilkZeroTicks;
    [Export] public int CoinZeroTicks;
    [Export] public int SampleCount;
    [Export] public int Houses;
    [Export] public int LoveHouses;
    [Export] public int SellPoints;
    [Export] public int FoodFarms;
    [Export] public int Helpers;
    [Export] public int Pets;
    [Export] public int Cows;
    [Export] public int HousedCows;
    [Export] public int WildCows;
    [Export] public int LandPlots;
    [Export] public int TotalLandCost;
    [Export] public int FinalStructureBuilt;
    [Export] public int PrevFood;
    [Export] public int PrevMilk;
    [Export] public int PrevCoins;
}
