// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class NavigationRegion2DNode : Node
{
    [Export] public uint NavigationLayers;
    [Export] public bool Enabled;
    [Export] public float TravelCost;
    [Export] public float EnterCost;
    [Export] public int VertexCount;
}
