// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class NavigationAgent2DNode : Node
{
    [Export] public Vector2 TargetPosition;
    [Export] public uint NavigationLayers;
    [Export] public float PathDesiredDistance;
    [Export] public float TargetDesiredDistance;
    [Export] public float MaxSpeed;
    [Export] public float Radius;
    [Export] public float AvoidanceLookahead;
    [Export] public bool AvoidanceEnabled;
    [Export] public uint AvoidanceMask;
    [Export] public int AvoidanceRayCount;
    [Export] public bool IsNavigationFinished;
    [Export] public bool IsTargetReachable;
    [Export] public bool IsTargetPositionChanged;
    [Export] public Vector2 Velocity;
    [Export] public Vector2 NextPathPosition;
    [Export] public float DistanceToTarget;
}
