// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class NavigationObstacle2DNode : Node
{
    [Export] public float Radius;
    [Export] public Vector2 Velocity;
    [Export] public bool AffectsNavigationMesh;
    [Export] public uint NavigationLayers;
}
