// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class NavigationWorld2DNode : Node
{
    [Export] public Vector2 BoundsMin;
    [Export] public Vector2 BoundsMax;
    [Export] public float CellSize;
    [Export] public float AgentRadius;
    [Export] public uint ObstacleMask;
    [Export] public bool IncludeDynamicBodies;
    [Export] public bool ForceBake;
    [Export] public float ChunkSize;
    [Export] public bool PhysicsBaked;
    [Export] public int LastObstacleHash;
    [Export] public int LastStaticBodyCount;
    [Export] public long DirtyTick;
}
