// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class NavMeshConstraintNode : Node
{
    [Export] public bool DisableSlide;
    [Export] public bool DisablePushOut;
    [Export] public float SlideFactor;
    [Export] public float MaxSlideAngleDegrees;
}
