// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class PlayerStateComponentNode : Node
{
    [Export] public Vector2 ReturnPosition;
    [Export] public int ClickMultiplier;
}
