// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class RigidBody2DNode : Node
{
    [Export] public float Mass;
    [Export] public float GravityScale;
    [Export] public float Inertia;
    [Export] public Vector2 LinearVelocity;
    [Export] public float AngularVelocity;
    [Export] public float LinearDamping;
    [Export] public float AngularDamping;
    [Export] public bool Freeze;
    [Export] public bool FreezeMode;
    [Export] public bool LockRotation;
    [Export] public bool Sleeping;
    [Export] public bool CcdEnabled;
    [Export] public uint CollisionLayer;
    [Export] public uint CollisionMask;
}
