// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class SleepingComponentNode : Node
{
    [Export] public int TicksRemaining;
    [Export] public int TotalTicks;
    [Export] public int DayAdvanced;
}
