// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

[Tool]
public partial class StaticBody2DNode : Node
{
    [Export] public uint CollisionLayer;
    [Export] public uint CollisionMask;
    [Export] public float PhysicsMaterialOverride;
    [Export] public bool ConstantLinearVelocity;
    [Export] public Vector2 ConstantLinearVelocityValue;
    [Export] public float ConstantAngularVelocityValue;
}
