// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

public partial class StateComponentNode : Node
{
    [Export] public int CurrentTime;
    [Export] public int MaxTime;
    [Export] public bool IsEnabled;
}
