// <auto-generated/>
using Godot;

namespace Template.Godot.Framework;

public partial class TestEntityComponentNode : Node
{
    [Export] public int Health;
    [Export] public int MaxHealth;
    [Export] public bool IsAlive;
}
