// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;
using Deterministic.GameFramework.Navigation2D.Components;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(CowComponent),
    typeof(CharacterBody2D),
    typeof(CollisionShape2D),
    typeof(StateComponent),
    typeof(SkinComponent),
    typeof(NavigationAgent2D))]
public static partial class CowDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<CowComponent>();

        ref var component = ref ctx.GetComponent<CowComponent>(entity);
        component.Exhaust = 0;
        component.MaxExhaust = 0;
        component.IsMilking = false;
        component.HouseId = Entity.Null;
        component.PreviousHouseId = Entity.Null;
        component.SpawnPosition = Vector2.Zero;
        component.FollowingPlayer = Entity.Null;
        component.FollowTarget = Entity.Null;
        component.PreferredFood = 0;
        component.IsDepressed = false;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = CharacterBody2D.Default;
        entityBody.CollisionLayer = 4u;
        entityBody.CollisionMask = 8u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateCircle(0.5f));

        var navAgent = NavigationAgent2D.Default;
        navAgent.MaxSpeed = 10f;
        navAgent.TargetDesiredDistance = 2f;
        navAgent.PathDesiredDistance = 1f;
        navAgent.Radius = 0.5f;
        navAgent.IsNavigationFinished = true;
        ctx.AddComponent(entity, navAgent);

        ctx.AddComponent(entity, new StateComponent
        {
            Key = "",
            CurrentTime = 0,
            MaxTime = 0,
            IsEnabled = false
        });

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<CowComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref CowComponent component, Dictionary<string, Entity> childEntities);
}
