// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;
using Deterministic.GameFramework.Navigation2D.Components;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(HelperComponent),
    typeof(CharacterBody2D),
    typeof(CollisionShape2D),
    typeof(StateComponent),
    typeof(SkinComponent),
    typeof(NavigationAgent2D))]
public static partial class HelperDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<HelperComponent>();

        ref var component = ref ctx.GetComponent<HelperComponent>(entity);
        component.Type = 0;
        component.OwnerPlayer = Entity.Null;
        component.State = 0;
        component.TargetEntity = Entity.Null;
        component.WorkTimer = 0;
        component.WorkDuration = 0;
        component.BagGrass = 0;
        component.BagCarrot = 0;
        component.BagApple = 0;
        component.BagMushroom = 0;
        component.BagMilk = 0;
        component.BagCarrotMilkshake = 0;
        component.BagVitaminMix = 0;
        component.BagPurplePotion = 0;
        component.BagCoins = 0;
        component.BagCapacity = 0;
        component.WantedFoodType = 0;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = CharacterBody2D.Default;
        entityBody.CollisionLayer = 4u;
        entityBody.CollisionMask = 8u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateCircle(0.5f));

        var navAgent = NavigationAgent2D.Default;
        navAgent.MaxSpeed = 10f;
        navAgent.TargetDesiredDistance = 2f;
        navAgent.PathDesiredDistance = 1f;
        navAgent.Radius = 0.5f;
        navAgent.IsNavigationFinished = true;
        ctx.AddComponent(entity, navAgent);

        ctx.AddComponent(entity, new StateComponent
        {
            Key = "",
            CurrentTime = 0,
            MaxTime = 0,
            IsEnabled = false
        });

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<HelperComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref HelperComponent component, Dictionary<string, Entity> childEntities);
}
