// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;
using Deterministic.GameFramework.Navigation2D.Components;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(HelperPetComponent),
    typeof(CharacterBody2D),
    typeof(CollisionShape2D),
    typeof(NavigationAgent2D))]
public static partial class HelperPetDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<HelperPetComponent>();

        ref var component = ref ctx.GetComponent<HelperPetComponent>(entity);
        component.FollowTarget = Entity.Null;
        component.HelperType = 0;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = CharacterBody2D.Default;
        entityBody.CollisionLayer = 4u;
        entityBody.CollisionMask = 8u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateCircle(0.5f));

        var navAgent = NavigationAgent2D.Default;
        navAgent.MaxSpeed = 10f;
        navAgent.TargetDesiredDistance = 2f;
        navAgent.PathDesiredDistance = 1f;
        navAgent.Radius = 0.5f;
        navAgent.IsNavigationFinished = true;
        ctx.AddComponent(entity, navAgent);

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<HelperPetComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref HelperPetComponent component, Dictionary<string, Entity> childEntities);
}
