// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(HouseComponent),
    typeof(StaticBody2D),
    typeof(CollisionShape2D))]
public static partial class HouseDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<HouseComponent>();

        ref var component = ref ctx.GetComponent<HouseComponent>(entity);
        component.CowId = Entity.Null;
        component.SelectedFood = 0;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = StaticBody2D.Default;
        entityBody.CollisionLayer = 1u;
        entityBody.CollisionMask = 1u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateRectangle(new Vector2(2f, 2f)));

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<HouseComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref HouseComponent component, Dictionary<string, Entity> childEntities);
}
