// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(LandComponent),
    typeof(StaticBody2D),
    typeof(CollisionShape2D))]
public static partial class LandDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<LandComponent>();

        ref var component = ref ctx.GetComponent<LandComponent>(entity);
        component.CurrentCoins = 0;
        component.Threshold = 0;
        component.Type = 0;
        component.Arm = 0;
        component.Ring = 0;
        component.Locked = 0;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = StaticBody2D.Default;
        entityBody.CollisionLayer = 4u;
        entityBody.CollisionMask = 8u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateRectangle(new Vector2(2f, 2f)));

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<LandComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref LandComponent component, Dictionary<string, Entity> childEntities);
}
