// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(LoveHouseComponent))]
public static partial class LoveHouseDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<LoveHouseComponent>();

        ref var component = ref ctx.GetComponent<LoveHouseComponent>(entity);
        component.CowId1 = Entity.Null;
        component.CowId2 = Entity.Null;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<LoveHouseComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref LoveHouseComponent component, Dictionary<string, Entity> childEntities);
}
