// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(GrassComponent),
    typeof(StaticBody2D),
    typeof(CollisionShape2D))]
public static partial class MushroomDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<GrassComponent>();

        ref var component = ref ctx.GetComponent<GrassComponent>(entity);
        component.Durability = 10;
        component.MaxDurability = 10;
        component.FoodType = 0;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = StaticBody2D.Default;
        entityBody.CollisionLayer = 4u;
        entityBody.CollisionMask = 8u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateCircle(1f));

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<GrassComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref GrassComponent component, Dictionary<string, Entity> childEntities);
}
