// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(PlayerEntity),
    typeof(PlayerStateComponent),
    typeof(CharacterBody2D),
    typeof(CollisionShape2D),
    typeof(StateComponent),
    typeof(SkinComponent))]
public static partial class PlayerDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<PlayerEntity>();

        ref var component = ref ctx.GetComponent<PlayerEntity>(entity);
        component.UserId = default;
        component.Id = Entity.Null;
        component.Name = "";

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = CharacterBody2D.Default;
        entityBody.CollisionLayer = 1u;
        entityBody.CollisionMask = 1u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateCircle(0.46962145f));

        ctx.AddComponent(entity, new StateComponent
        {
            Key = "",
            CurrentTime = 0,
            MaxTime = 0,
            IsEnabled = false
        });

        ctx.AddComponent(entity, new PlayerStateComponent
        {
            InteractionTarget = Entity.Null,
            InteractionTarge10 = Entity.Null,
            ReturnPosition = Vector2.Zero,
            InteractionZone = Entity.Null,
            FollowingCow = Entity.Null,
        });

        // Child entity: InteractionZone
        var interactionZone = ctx.State.CreateEntity();
        var interactionZoneTransform = new Transform2D(Vector2.Zero, 0, Vector2.One);
        interactionZoneTransform.Parent = entity;
        interactionZoneTransform.DestroyOnUnparent = true;
        ctx.State.AddComponent(interactionZone, interactionZoneTransform);
        ctx.State.AddComponent(interactionZone, new Area2D
        {
            Monitoring = true,
            Monitorable = false,
            CollisionLayer = 8u,
            CollisionMask = 5u,
            OverlappingEntities = new List8<int>(),
        });
        ctx.State.AddComponent(interactionZone, CollisionShape2D.CreateCircle(2f));
        ref var interactionZoneTarget = ref ctx.GetComponent<PlayerStateComponent>(entity);
        interactionZoneTarget.InteractionZone = interactionZone;

        var childEntities = new Dictionary<string, Entity>
        {
            { "InteractionZone", interactionZone },
        };
        component = ref ctx.GetComponent<PlayerEntity>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref PlayerEntity component, Dictionary<string, Entity> childEntities);
}
