// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;
using Deterministic.GameFramework.Navigation2D.Components;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(TestEntityComponent),
    typeof(CharacterBody2D),
    typeof(CollisionShape2D),
    typeof(StateComponent),
    typeof(SkinComponent),
    typeof(NavigationAgent2D))]
public static partial class TestEntityDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<TestEntityComponent>();

        ref var component = ref ctx.GetComponent<TestEntityComponent>(entity);
        component.Health = 100;
        component.MaxHealth = 100;
        component.Speed = default;
        component.IsAlive = true;
        component.Target = Entity.Null;

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = CharacterBody2D.Default;
        entityBody.CollisionLayer = 1u;
        entityBody.CollisionMask = 3u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateCircle(0.75f));

        var navAgent = NavigationAgent2D.Default;
        navAgent.MaxSpeed = 15f;
        navAgent.TargetDesiredDistance = 2f;
        navAgent.PathDesiredDistance = 1f;
        navAgent.Radius = 0.6f;
        navAgent.IsNavigationFinished = true;
        ctx.AddComponent(entity, navAgent);

        ctx.AddComponent(entity, new StateComponent
        {
            Key = "",
            CurrentTime = 0,
            MaxTime = 0,
            IsEnabled = false
        });

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<TestEntityComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref TestEntityComponent component, Dictionary<string, Entity> childEntities);
}
