<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MlBot.Lib</RootNamespace>
    <AssemblyName>MlBot.Lib</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Framework\Core\Deterministic.GameFramework.Common\Deterministic.GameFramework.Common.csproj" />
    <ProjectReference Include="..\..\Framework\2D\Deterministic.GameFramework.TwoD.Physics\Deterministic.GameFramework.TwoD.Physics.csproj" />
    <ProjectReference Include="..\..\Framework\2D\Deterministic.GameFramework.TwoD.Navigation\Deterministic.GameFramework.TwoD.Navigation.csproj" />
    <ProjectReference Include="..\..\Template.Shared\Template.Shared.csproj" />
  </ItemGroup>

</Project>
