// <auto-generated/>
using Deterministic.GameFramework.DAR;
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.Reactive;
using Template.Shared.Components;
using Deterministic.GameFramework.TwoD;
using R3;

namespace Template.Godot.Visuals;

public partial class HelperAssistantViewModel : EntityViewModel
{
    public HelperAssistantDefinitionModel HelperAssistant { get; }

    public HelperAssistantViewModel(Context context) : base(context)
    {
        HelperAssistant = new HelperAssistantDefinitionModel(ReactiveSystem.Instance, context);
        Disposables.Add(HelperAssistant);

        OnInitialize(context);
        OnCreated();
    }

    /// <summary>Called after all generated properties are initialized. Use to set up custom reactive bindings.</summary>
    partial void OnInitialize(Context context);
    partial void OnCreated();
}
