using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

/// <summary>
/// Generates [Tool] Node wrappers for IComponent structs.
/// These are added as children of FrameworkEntity in the Godot editor
/// to declare which components an entity has, with [Export] fields for simple types.
/// </summary>
public static class ComponentNodeGenerator
{
    // Types exported directly (no mapping needed)
    private static readonly HashSet<string> DirectExportTypes = new()
    {
        "int", "bool", "float", "byte", "string", "double", "long", "uint"
    };

    // Framework types mapped to Godot-compatible export types
    private static readonly Dictionary<string, string> MappedExportTypes = new()
    {
        { "FixedString32", "string" },
        { "System.Guid", "string" },
        { "Vector2", "Vector2" },
        { "Float", "float" },
    };

    // Types that are skipped (not useful in editor)
    private static readonly HashSet<string> SkippedTypes = new()
    {
        "Entity",
    };

    // Fields that shadow Godot.Node base members
    private static readonly HashSet<string> NodeBaseMembers = new()
    {
        "Name", "Owner", "ProcessMode", "ProcessPriority",
        "PhysicsProcessPriority", "ProcessThreadGroup",
    };

    public static string Generate(ComponentDescriptor component)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Godot;");
        sb.AppendLine();
        sb.AppendLine("namespace Template.Godot.Framework;");
        sb.AppendLine();
        sb.AppendLine("[Tool]");
        sb.AppendLine($"public partial class {component.ComponentName}Node : Node");
        sb.AppendLine("{");

        foreach (var field in component.Fields)
        {
            if (SkippedTypes.Contains(field.TypeName))
                continue;

            string? exportType = null;

            if (DirectExportTypes.Contains(field.TypeName))
                exportType = field.TypeName;
            else if (MappedExportTypes.TryGetValue(field.TypeName, out var mapped))
                exportType = mapped;
            else if (field.IsEnum)
                exportType = "int";

            if (exportType != null)
            {
                var newKeyword = NodeBaseMembers.Contains(field.Name) ? "new " : "";
                string exportAttr;
                if (field.IsEnum && field.EnumHint != null)
                {
                    var hint = field.EnumIsFlags ? "PropertyHint.Flags" : "PropertyHint.Enum";
                    exportAttr = $"[Export({hint}, \"{field.EnumHint}\")]";
                }
                else
                {
                    exportAttr = "[Export]";
                }

                if (field.DefaultValue != null)
                    sb.AppendLine($"    {exportAttr} public {newKeyword}{exportType} {field.Name} = {field.DefaultValue};");
                else
                    sb.AppendLine($"    {exportAttr} public {newKeyword}{exportType} {field.Name};");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
