using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

public static class ComponentGenerator
{
    private static readonly Dictionary<string, string> TypeMap = new()
    {
        ["int"] = "int",
        ["bool"] = "bool",
        ["float"] = "float",
        ["byte"] = "byte",
        ["Entity"] = "Entity",
        ["Vector2"] = "Vector2",
        ["string"] = "FixedString32",
        ["FixedString32"] = "FixedString32",
    };

    public static string Generate(ComponentDescriptor component)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Deterministic.GameFramework.ECS;");
        sb.AppendLine("using Deterministic.GameFramework.TwoD;");
        sb.AppendLine("using Deterministic.GameFramework.Types;");
        sb.AppendLine("using System.Runtime.InteropServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Template.Shared.Components;");
        sb.AppendLine();
        sb.AppendLine("[StructLayout(LayoutKind.Sequential, Pack = 1)]");
        sb.AppendLine($"[StableId(\"{component.StableId}\")]");
        sb.AppendLine($"public struct {component.ComponentName} : IComponent");
        sb.AppendLine("{");

        foreach (var field in component.Fields)
        {
            var csType = MapType(field.TypeName);
            sb.AppendLine($"    public {csType} {field.Name};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string MapType(string typeName)
    {
        return TypeMap.TryGetValue(typeName, out var mapped) ? mapped : typeName;
    }
}
