using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

/// <summary>
/// Generates [Tool] Node wrappers for IComponent structs.
/// These are added as children of FrameworkEntity in the Godot editor
/// to declare which components an entity has, with [Export] fields for simple types.
/// </summary>
public static class ComponentNodeGenerator
{
    private static readonly HashSet<string> ExportableTypes = new()
    {
        "int", "bool", "float", "byte", "string", "double", "long"
    };

    public static string Generate(ComponentDescriptor component)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Godot;");
        sb.AppendLine();
        sb.AppendLine("namespace Template.Godot.Framework;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {component.ComponentName}Node : Node");
        sb.AppendLine("{");

        foreach (var field in component.Fields)
        {
            if (ExportableTypes.Contains(field.TypeName))
            {
                if (field.DefaultValue != null)
                    sb.AppendLine($"    [Export] public {field.TypeName} {field.Name} = {field.DefaultValue};");
                else
                    sb.AppendLine($"    [Export] public {field.TypeName} {field.Name};");
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }
}
