using System.Globalization;
using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

public static class DefinitionGenerator
{
    public static string Generate(EntityDescriptor entity)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Deterministic.GameFramework.ECS;");
        sb.AppendLine("using Deterministic.GameFramework.TwoD;");
        sb.AppendLine("using Deterministic.GameFramework.Physics2D.Components;");
        sb.AppendLine("using Deterministic.GameFramework.Types;");
        sb.AppendLine("using Deterministic.GameFramework.Reactive;");
        sb.AppendLine("using Deterministic.GameFramework.DAR;");
        sb.AppendLine("using Template.Shared.Components;");
        sb.AppendLine("using System.Collections.Generic;");

        if (entity.NavAgent != null)
            sb.AppendLine("using Deterministic.GameFramework.Navigation2D.Components;");

        sb.AppendLine();
        sb.AppendLine("namespace Template.Shared.Definitions;");
        sb.AppendLine();

        var componentTypes = BuildComponentTypeList(entity);
        sb.AppendLine("[EntityDefinition(");
        for (int i = 0; i < componentTypes.Count; i++)
        {
            var comma = i < componentTypes.Count - 1 ? "," : ")]";
            sb.AppendLine($"    typeof({componentTypes[i]}){comma}");
        }

        var primaryComponent = entity.Components.FirstOrDefault()?.ComponentName ?? entity.EntityName + "Component";

        sb.AppendLine($"public static partial class {entity.EntityName}Definition");
        sb.AppendLine("{");
        sb.AppendLine($"    public static Entity Create(Context ctx, Vector2 position)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var entity = ctx.CreateEntity<{primaryComponent}>();");
        sb.AppendLine();

        if (entity.Components.Count > 0)
        {
            var primary = entity.Components[0];
            sb.AppendLine($"        ref var component = ref ctx.GetComponent<{primary.ComponentName}>(entity);");
            if (primary.Fields.Count > 0)
            {
                foreach (var field in primary.Fields)
                    sb.AppendLine($"        component.{field.Name} = {GetDefaultValue(field)};");
            }
            sb.AppendLine();
        }

        sb.AppendLine("        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));");

        if (entity.Physics != null)
        {
            sb.AppendLine();
            GeneratePhysicsForTarget(sb, entity.Physics, "entity", "ctx");
            sb.AppendLine();
            if (entity.Physics.ShapeType == CollisionShapeType.Circle)
                sb.AppendLine($"        ctx.AddComponent(entity, CollisionShape2D.CreateCircle({entity.Physics.ShapeRadius.ToString(CultureInfo.InvariantCulture)}f));");
            else
                sb.AppendLine($"        ctx.AddComponent(entity, CollisionShape2D.CreateRectangle(new Vector2({entity.Physics.ShapeWidth.ToString(CultureInfo.InvariantCulture)}f, {entity.Physics.ShapeHeight.ToString(CultureInfo.InvariantCulture)}f)));");
        }

        if (entity.NavAgent != null)
        {
            sb.AppendLine();
            sb.AppendLine("        var navAgent = NavigationAgent2D.Default;");
            sb.AppendLine($"        navAgent.MaxSpeed = {entity.NavAgent.MaxSpeed.ToString(CultureInfo.InvariantCulture)}f;");
            sb.AppendLine($"        navAgent.TargetDesiredDistance = {entity.NavAgent.TargetDesiredDistance.ToString(CultureInfo.InvariantCulture)}f;");
            sb.AppendLine($"        navAgent.PathDesiredDistance = {entity.NavAgent.PathDesiredDistance.ToString(CultureInfo.InvariantCulture)}f;");
            sb.AppendLine($"        navAgent.Radius = {entity.NavAgent.Radius.ToString(CultureInfo.InvariantCulture)}f;");
            sb.AppendLine("        navAgent.IsNavigationFinished = true;");
            sb.AppendLine("        ctx.AddComponent(entity, navAgent);");
        }

        if (entity.HasState)
        {
            sb.AppendLine();
            sb.AppendLine("        ctx.AddComponent(entity, new StateComponent");
            sb.AppendLine("        {");
            sb.AppendLine("            Key = \"\",");
            sb.AppendLine("            CurrentTime = 0,");
            sb.AppendLine("            MaxTime = 0,");
            sb.AppendLine("            IsEnabled = false");
            sb.AppendLine("        });");
        }

        for (int i = 1; i < entity.Components.Count; i++)
        {
            var comp = entity.Components[i];
            sb.AppendLine();
            if (comp.IsMarkerComponent)
            {
                sb.AppendLine($"        ctx.AddComponent(entity, new {comp.ComponentName}());");
            }
            else
            {
                sb.AppendLine($"        ctx.AddComponent(entity, new {comp.ComponentName}");
                sb.AppendLine("        {");
                foreach (var field in comp.Fields)
                    sb.AppendLine($"            {field.Name} = {GetDefaultValue(field)},");
                sb.AppendLine("        });");
            }
        }

        // Child entities — created before OnEntityCreated so all components exist
        foreach (var child in entity.ChildEntities)
            GenerateChildEntity(sb, child);

        sb.AppendLine();
        sb.AppendLine("        var childEntities = new Dictionary<string, Entity>");
        sb.AppendLine("        {");
        foreach (var child in entity.ChildEntities)
            sb.AppendLine($"            {{ \"{child.ChildName}\", {ToCamelCase(child.ChildName)} }},");
        sb.AppendLine("        };");

        // Re-acquire ref in case AddComponent calls invalidated it
        if (entity.Components.Count > 0)
            sb.AppendLine($"        component = ref ctx.GetComponent<{primaryComponent}>(entity);");

        // OnEntityCreated hook
        sb.AppendLine();
        if (entity.Components.Count > 0)
            sb.AppendLine($"        OnEntityCreated(ctx, entity, ref component, childEntities);");
        else
            sb.AppendLine($"        OnEntityCreated(ctx, entity, childEntities);");

        sb.AppendLine();
        sb.AppendLine("        return entity;");
        sb.AppendLine("    }");

        // Partial method declaration
        sb.AppendLine();
        if (entity.Components.Count > 0)
            sb.AppendLine($"    static partial void OnEntityCreated(Context ctx, Entity entity, ref {primaryComponent} component, Dictionary<string, Entity> childEntities);");
        else
            sb.AppendLine($"    static partial void OnEntityCreated(Context ctx, Entity entity, Dictionary<string, Entity> childEntities);");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateChildEntity(StringBuilder sb, ChildEntityDescriptor child)
    {
        var varName = ToCamelCase(child.ChildName);

        sb.AppendLine();
        sb.AppendLine($"        // Child entity: {child.ChildName}");
        sb.AppendLine($"        var {varName} = ctx.State.CreateEntity();");

        if (child.ParentToEntity)
        {
            sb.AppendLine($"        var {varName}Transform = new Transform2D(Vector2.Zero, 0, Vector2.One);");
            sb.AppendLine($"        {varName}Transform.Parent = entity;");
            if (child.DestroyOnUnparent)
                sb.AppendLine($"        {varName}Transform.DestroyOnUnparent = true;");
            sb.AppendLine($"        ctx.State.AddComponent({varName}, {varName}Transform);");
        }

        if (child.Physics != null)
        {
            GeneratePhysicsForTarget(sb, child.Physics, varName, "ctx.State");

            if (child.Physics.ShapeType == CollisionShapeType.Circle)
                sb.AppendLine($"        ctx.State.AddComponent({varName}, CollisionShape2D.CreateCircle({child.Physics.ShapeRadius.ToString(CultureInfo.InvariantCulture)}f));");
            else
                sb.AppendLine($"        ctx.State.AddComponent({varName}, CollisionShape2D.CreateRectangle(new Vector2({child.Physics.ShapeWidth.ToString(CultureInfo.InvariantCulture)}f, {child.Physics.ShapeHeight.ToString(CultureInfo.InvariantCulture)}f)));");
        }

        if (!string.IsNullOrEmpty(child.StoreInField))
        {
            if (!string.IsNullOrEmpty(child.StoreInComponent))
            {
                sb.AppendLine($"        ref var {varName}Target = ref ctx.GetComponent<{child.StoreInComponent}>(entity);");
                sb.AppendLine($"        {varName}Target.{child.StoreInField} = {varName};");
            }
            else
            {
                sb.AppendLine($"        component.{child.StoreInField} = {varName};");
            }
        }
    }

    private static void GeneratePhysicsForTarget(StringBuilder sb, PhysicsConfig physics, string target, string ctx)
    {
        if (physics.BodyType == PhysicsBodyType.Area2D)
        {
            sb.AppendLine($"        {ctx}.AddComponent({target}, new Area2D");
            sb.AppendLine("        {");
            sb.AppendLine($"            Monitoring = {(physics.Monitoring ? "true" : "false")},");
            sb.AppendLine($"            Monitorable = {(physics.Monitorable ? "true" : "false")},");
            sb.AppendLine($"            CollisionLayer = {physics.CollisionLayer}u,");
            sb.AppendLine($"            CollisionMask = {physics.CollisionMask}u,");
            sb.AppendLine("            OverlappingEntities = new List8<int>(),");
            sb.AppendLine("        });");
        }
        else
        {
            sb.AppendLine($"        var {target}Body = {physics.BodyType}.Default;");
            sb.AppendLine($"        {target}Body.CollisionLayer = {physics.CollisionLayer}u;");
            sb.AppendLine($"        {target}Body.CollisionMask = {physics.CollisionMask}u;");
            sb.AppendLine($"        {ctx}.AddComponent({target}, {target}Body);");
        }
    }

    private static List<string> BuildComponentTypeList(EntityDescriptor entity)
    {
        var types = new List<string> { "Transform2D" };
        foreach (var comp in entity.Components) types.Add(comp.ComponentName);
        if (entity.Physics != null) { types.Add(entity.Physics.BodyType.ToString()); types.Add("CollisionShape2D"); }
        if (entity.HasState) types.Add("StateComponent");
        if (entity.HasSkin) types.Add("SkinComponent");
        if (entity.NavAgent != null) types.Add("NavigationAgent2D");
        foreach (var extra in entity.ExtraComponentTypes)
            if (!types.Contains(extra)) types.Add(extra);
        return types;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }

    private static string GetDefaultValue(FieldDescriptor field)
    {
        if (field.DefaultValue != null)
        {
            if (field.TypeName == "float" && !field.DefaultValue.EndsWith("f", StringComparison.OrdinalIgnoreCase))
                return field.DefaultValue + "f";
            // For enum fields with a plain numeric default, cast to the enum type
            if (field.IsEnum && int.TryParse(field.DefaultValue, out _))
                return $"({field.TypeName}){field.DefaultValue}";
            return field.DefaultValue;
        }
        return field.TypeName switch
        {
            "int" => "0",
            "bool" => "false",
            "float" => "0f",
            "byte" => "0",
            "Entity" => "Entity.Null",
            "Vector2" => "Vector2.Zero",
            "string" or "FixedString32" => "\"\"",
            _ => "default"
        };
    }
}
