using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

public static class ViewModelGenerator
{
    public static string Generate(EntityDescriptor entity)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Deterministic.GameFramework.DAR;");
        sb.AppendLine("using Deterministic.GameFramework.ECS;");
        sb.AppendLine("using Deterministic.GameFramework.Reactive;");
        sb.AppendLine("using Template.Shared.Components;");
        sb.AppendLine("using Deterministic.GameFramework.TwoD;");
        sb.AppendLine("using R3;");
        sb.AppendLine();
        sb.AppendLine("namespace Template.Godot.Visuals;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {entity.EntityName}ViewModel : EntityViewModel");
        sb.AppendLine("{");

        sb.AppendLine($"    public {entity.EntityName}DefinitionModel {entity.EntityName} {{ get; }}");

        if (entity.HasSkin)
        {
            sb.AppendLine("    public SkinComponentModel Skin { get; }");
            sb.AppendLine("    public ReactiveProperty<bool> IsHidden { get; } = new();");
        }

        sb.AppendLine();
        sb.AppendLine($"    public {entity.EntityName}ViewModel(Context context) : base(context)");
        sb.AppendLine("    {");
        sb.AppendLine($"        {entity.EntityName} = new {entity.EntityName}DefinitionModel(ReactiveSystem.Instance, context);");
        sb.AppendLine($"        Disposables.Add({entity.EntityName});");

        if (entity.HasSkin)
        {
            sb.AppendLine();
            sb.AppendLine($"        if (context.State.HasComponent<SkinComponent>(Entity))");
            sb.AppendLine("        {");
            sb.AppendLine("            Skin = new SkinComponentModel(ReactiveSystem.Instance, context);");
            sb.AppendLine("            Disposables.Add(Skin);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        ReactiveSystem.Instance.ObserveAdd<HiddenComponent>().Where(x => x == Entity).Subscribe(_ => IsHidden.Value = true).AddTo(Disposables);");
            sb.AppendLine("        ReactiveSystem.Instance.ObserveRemove<HiddenComponent>().Where(x => x == Entity).Subscribe(_ => IsHidden.Value = false).AddTo(Disposables);");
        }

        sb.AppendLine();
        sb.AppendLine("        OnInitialize(context);");
        sb.AppendLine("        OnCreated();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Called after all generated properties are initialized. Use to set up custom reactive bindings.</summary>");
        sb.AppendLine("    partial void OnInitialize(Context context);");
        sb.AppendLine("    partial void OnCreated();");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
