using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

/// <summary>
/// Generates one {Entity}View.g.cs per entity — a self-contained Node3D that
/// registers its ObservableList, spawns/despawns visuals, and exposes partial hooks.
/// Replaces the monolithic VisualizerGenerator.
/// </summary>
public static class ViewGenerator
{
    public static string Generate(EntityDescriptor entity)
    {
        var sb = new StringBuilder();
        var primaryComponent = entity.Components.FirstOrDefault()?.ComponentName ?? entity.EntityName + "Component";
        var camel = ToCamelCase(entity.EntityName);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Godot;");
        sb.AppendLine("using R3;");
        sb.AppendLine("using ObservableCollections;");
        sb.AppendLine("using Template.Godot.Core;");
        sb.AppendLine("using Template.Shared.Components;");
        sb.AppendLine("using Deterministic.GameFramework.Reactive;");
        sb.AppendLine("using Deterministic.GameFramework.DAR;");
        sb.AppendLine("using DTransform2D = Deterministic.GameFramework.TwoD.Transform2D;");
        sb.AppendLine("using GVector3 = Godot.Vector3;");
        sb.AppendLine();
        sb.AppendLine("namespace Template.Godot.Visuals;");
        sb.AppendLine();
        sb.AppendLine($"public partial class {entity.EntityName}View : Node3D");
        sb.AppendLine("{");

        // Export prefab
        sb.AppendLine($"    [Export] public PackedScene Prefab;");
        sb.AppendLine();
        sb.AppendLine("    private readonly CompositeDisposable _disposables = new();");
        sb.AppendLine($"    private readonly Dictionary<{entity.EntityName}ViewModel, Node3D> _spawnedEntities = new();");
        sb.AppendLine();

        // _Ready — register
        sb.AppendLine("    private bool _registered;");
        sb.AppendLine();
        sb.AppendLine("    public override void _Ready()");
        sb.AppendLine("    {");
        sb.AppendLine("        if (GameManager.Instance != null && GameManager.Instance.IsGameRunning)");
        sb.AppendLine("        {");
        sb.AppendLine("            Register();");
        sb.AppendLine("            SetProcess(false);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public override void _Process(double delta)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_registered || GameManager.Instance == null || !GameManager.Instance.IsGameRunning) return;");
        sb.AppendLine("        SetProcess(false);");
        sb.AppendLine("        Register();");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Register
        sb.AppendLine("    private void Register()");
        sb.AppendLine("    {");
        sb.AppendLine("        _registered = true;");
        sb.AppendLine("        var client = GameManager.Instance.GameClient;");
        sb.AppendLine($"        var list = client.Reactive.ObservableList<{primaryComponent}, DTransform2D, {entity.EntityName}ViewModel>(");
        sb.AppendLine($"            ctx => new {entity.EntityName}ViewModel(ctx),");
        sb.AppendLine("            _disposables");
        sb.AppendLine("        );");
        sb.AppendLine();
        sb.AppendLine("        list.ObserveAdd().Subscribe(e => Callable.From(() => OnAdded(e.Value)).CallDeferred()).AddTo(_disposables);");
        sb.AppendLine("        list.ObserveRemove().Subscribe(e => Callable.From(() => OnRemoved(e.Value)).CallDeferred()).AddTo(_disposables);");
        sb.AppendLine("        list.ObserveReset().Subscribe(_ => Callable.From(OnReset).CallDeferred()).AddTo(_disposables);");
        sb.AppendLine("        // Spawn existing entities (deduped by ContainsKey in OnAdded)");
        sb.AppendLine("        foreach (var vm in list) OnAdded(vm);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // OnAdded
        sb.AppendLine($"    private void OnAdded({entity.EntityName}ViewModel vm)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_spawnedEntities.ContainsKey(vm)) return;");
        sb.AppendLine();
        sb.AppendLine("        var visualNode = Prefab?.Instantiate<Node3D>() ?? CreateFallbackVisual();");

        // Visual bindings
        foreach (var binding in entity.VisualBindings)
        {
            sb.AppendLine();
            var compPropName = StripComponentSuffix(entity.Components[0].ComponentName);
            var fieldAccess = $"vm.{entity.EntityName}.{compPropName}.{binding.ComponentField}";
            sb.AppendLine($"        {fieldAccess}.Subscribe(val =>");
            sb.AppendLine("        {");
            sb.AppendLine("            Callable.From(() =>");
            sb.AppendLine("            {");
            sb.AppendLine("                if (!IsInstanceValid(visualNode)) return;");
            sb.AppendLine($"                var target = visualNode.GetNodeOrNull<Node3D>(\"{binding.TargetNodePath}\");");
            sb.AppendLine($"                target?.SetDeferred(\"{binding.TargetProperty}\", val.ToString());");
            sb.AppendLine("            }).CallDeferred();");
            sb.AppendLine("        }).AddTo(vm.Disposables);");
        }

        // Skin
        if (entity.HasSkin)
        {
            sb.AppendLine();
            sb.AppendLine("        if (vm.Skin != null)");
            sb.AppendLine("        {");
            sb.AppendLine("            vm.Skin.Skins.Subscribe(skins =>");
            sb.AppendLine("            {");
            sb.AppendLine("                SkinVisualizer.UpdateSkins(visualNode, skins);");
            sb.AppendLine("            }).AddTo(vm.Disposables);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        vm.IsHidden.Subscribe(hidden =>");
            sb.AppendLine("        {");
            sb.AppendLine("            if (IsInstanceValid(visualNode)) visualNode.SetDeferred(\"visible\", !hidden);");
            sb.AppendLine("        }).AddTo(vm.Disposables);");
        }

        sb.AppendLine();
        sb.AppendLine("        AddChild(visualNode);");
        sb.AppendLine("        _spawnedEntities[vm] = visualNode;");
        sb.AppendLine("        var pos = vm.Transform.Position.CurrentValue;");
        sb.AppendLine("        visualNode.SetDeferred(\"position\", new GVector3((float)pos.X, 0f, (float)pos.Y));");
        sb.AppendLine();
        sb.AppendLine("        OnSpawned(vm, visualNode);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // OnRemoved
        sb.AppendLine($"    private void OnRemoved({entity.EntityName}ViewModel vm)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_spawnedEntities.TryGetValue(vm, out var node))");
        sb.AppendLine("        {");
        sb.AppendLine("            if (IsInstanceValid(node)) { node.Visible = false; node.QueueFree(); }");
        sb.AppendLine("            _spawnedEntities.Remove(vm);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        // OnReset
        sb.AppendLine("    private void OnReset()");
        sb.AppendLine("    {");
        sb.AppendLine($"        foreach (var vm in new List<{entity.EntityName}ViewModel>(_spawnedEntities.Keys))");
        sb.AppendLine("            OnRemoved(vm);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Fallback visual
        sb.AppendLine("    private static Node3D CreateFallbackVisual()");
        sb.AppendLine("    {");
        sb.AppendLine("        var node = new Node3D();");
        sb.AppendLine("        var meshInstance = new MeshInstance3D();");
        sb.AppendLine("        var mesh = new CylinderMesh { TopRadius = 0.5f, BottomRadius = 0.5f, Height = 0.1f };");
        sb.AppendLine("        mesh.Material = new StandardMaterial3D { AlbedoColor = Colors.White };");
        sb.AppendLine("        meshInstance.Mesh = mesh;");
        sb.AppendLine("        node.AddChild(meshInstance);");
        sb.AppendLine("        return node;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Partial hooks
        sb.AppendLine("    /// <summary>Called after entity visual is spawned and positioned. Add custom bindings here.</summary>");
        sb.AppendLine($"    partial void OnSpawned({entity.EntityName}ViewModel vm, Node3D visualNode);");
        sb.AppendLine();

        // Cleanup
        sb.AppendLine("    public override void _ExitTree()");
        sb.AppendLine("    {");
        sb.AppendLine("        _disposables.Dispose();");
        sb.AppendLine("        _spawnedEntities.Clear();");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string StripComponentSuffix(string name)
    {
        return name.EndsWith("Component") ? name[..^"Component".Length] : name;
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
