using System.Text;
using Template.CodeGen.Models;

namespace Template.CodeGen.Generators;

public static class VisualizerGenerator
{
    public static string Generate(List<EntityDescriptor> entities)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Godot;");
        sb.AppendLine("using R3;");
        sb.AppendLine("using ObservableCollections;");
        sb.AppendLine("using Template.Godot.Core;");
        sb.AppendLine("using Template.Shared.Components;");
        sb.AppendLine("using DTransform2D = Deterministic.GameFramework.TwoD.Transform2D;");
        sb.AppendLine("using GVector3 = Godot.Vector3;");
        sb.AppendLine();
        sb.AppendLine("namespace Template.Godot.Visuals;");
        sb.AppendLine();
        sb.AppendLine("public partial class EntityVisualizer");
        sb.AppendLine("{");

        foreach (var entity in entities)
            sb.AppendLine($"    [Export] public PackedScene {entity.EntityName}Prefab_Generated;");

        sb.AppendLine();
        sb.AppendLine("    private Dictionary<Type, Func<EntityViewModel, bool>> _spawnDispatch;");
        sb.AppendLine();

        // RegisterGeneratedEntities
        sb.AppendLine("    private void RegisterGeneratedEntities()");
        sb.AppendLine("    {");
        sb.AppendLine("        var client = GameManager.Instance.GameClient;");
        sb.AppendLine();
        sb.AppendLine("        _spawnDispatch = new Dictionary<Type, Func<EntityViewModel, bool>>");
        sb.AppendLine("        {");
        foreach (var entity in entities)
            sb.AppendLine($"            {{ typeof({entity.EntityName}ViewModel), vm => Spawn{entity.EntityName}(({entity.EntityName}ViewModel)vm) }},");
        sb.AppendLine("        };");
        sb.AppendLine();

        foreach (var entity in entities)
        {
            var primaryComponent = entity.Components.FirstOrDefault()?.ComponentName ?? entity.EntityName + "Component";
            var varName = ToCamelCase(entity.EntityName) + "s";

            sb.AppendLine($"        var {varName} = client.Reactive.ObservableList<{primaryComponent}, DTransform2D, {entity.EntityName}ViewModel>(");
            sb.AppendLine($"            ctx => new {entity.EntityName}ViewModel(ctx),");
            sb.AppendLine("            _disposables");
            sb.AppendLine("        );");
            sb.AppendLine();
            sb.AppendLine($"        {varName}.ObserveAdd().Subscribe(e => OnEntityAdded(e.Value)).AddTo(_disposables);");
            sb.AppendLine($"        {varName}.ObserveRemove().Subscribe(e => OnEntityRemoved(e.Value)).AddTo(_disposables);");
            sb.AppendLine($"        {varName}.ObserveReset().Subscribe(_ => OnListReset()).AddTo(_disposables);");
            sb.AppendLine($"        foreach (var vm in {varName}) OnEntityAdded(vm);");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // SpawnGeneratedEntity - dictionary dispatch
        sb.AppendLine("    private bool SpawnGeneratedEntity(EntityViewModel vm)");
        sb.AppendLine("    {");
        sb.AppendLine("        return _spawnDispatch.TryGetValue(vm.GetType(), out var spawner) && spawner(vm);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Per-entity spawn methods
        foreach (var entity in entities)
        {
            var camel = ToCamelCase(entity.EntityName);

            sb.AppendLine($"    private bool Spawn{entity.EntityName}({entity.EntityName}ViewModel {camel}Vm)");
            sb.AppendLine("    {");
            sb.AppendLine($"        var visualNode = {entity.EntityName}Prefab_Generated?.Instantiate<Node3D>() ?? CreateFallbackVisual(Colors.White, 0.5f);");

            foreach (var binding in entity.VisualBindings)
            {
                sb.AppendLine();
                var fieldAccess = $"{camel}Vm.{entity.EntityName}.{entity.Components[0].ComponentName}.{binding.ComponentField}";
                sb.AppendLine($"        {fieldAccess}.Subscribe(val =>");
                sb.AppendLine("        {");
                sb.AppendLine("            Callable.From(() =>");
                sb.AppendLine("            {");
                sb.AppendLine("                if (!IsInstanceValid(visualNode)) return;");
                sb.AppendLine($"                var target = visualNode.GetNodeOrNull<Node3D>(\"{binding.TargetNodePath}\");");
                sb.AppendLine($"                target?.SetDeferred(\"{binding.TargetProperty}\", val.ToString());");
                sb.AppendLine("            }).CallDeferred();");
                sb.AppendLine($"        }}).AddTo({camel}Vm.Disposables);");
            }

            if (entity.HasSkin)
            {
                sb.AppendLine();
                sb.AppendLine($"        if ({camel}Vm.Skin != null)");
                sb.AppendLine("        {");
                sb.AppendLine($"            {camel}Vm.Skin.Skins.Subscribe(skins =>");
                sb.AppendLine("            {");
                sb.AppendLine("                SkinVisualizer.UpdateSkins(visualNode, skins);");
                sb.AppendLine($"            }}).AddTo({camel}Vm.Disposables);");
                sb.AppendLine("        }");
                sb.AppendLine();
                sb.AppendLine($"        {camel}Vm.IsHidden.Subscribe(hidden =>");
                sb.AppendLine("        {");
                sb.AppendLine("            if (IsInstanceValid(visualNode)) visualNode.SetDeferred(\"visible\", !hidden);");
                sb.AppendLine($"        }}).AddTo({camel}Vm.Disposables);");
            }

            sb.AppendLine();
            sb.AppendLine($"        OnSpawn{entity.EntityName}({camel}Vm, visualNode);");
            sb.AppendLine($"        SetupCommonBindings({camel}Vm, visualNode);");
            sb.AppendLine("        return true;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        // SetupCommonBindings
        sb.AppendLine("    private void SetupCommonBindings(EntityViewModel vm, Node3D visualNode)");
        sb.AppendLine("    {");
        sb.AppendLine("        AddChild(visualNode);");
        sb.AppendLine("        _spawnedEntities[vm] = visualNode;");
        sb.AppendLine("        var pos = vm.Transform.Position.CurrentValue;");
        sb.AppendLine("        visualNode.SetDeferred(\"position\", new GVector3((float)pos.X, 0f, (float)pos.Y));");
        sb.AppendLine("        OnEntitySpawned(vm, visualNode);");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var entity in entities)
            sb.AppendLine($"    partial void OnSpawn{entity.EntityName}({entity.EntityName}ViewModel vm, Node3D visualNode);");

        sb.AppendLine("    partial void OnEntitySpawned(EntityViewModel vm, Node3D visualNode);");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToLowerInvariant(name[0]) + name[1..];
    }
}
