using FluentAssertions;
using Template.CodeGen.Generators;
using Template.CodeGen.Models;
using Xunit;

namespace Template.CodeGen.Tests;

public class ComponentGeneratorTests
{
    [Fact]
    public void Generate_ContainsStructLayout()
    {
        var comp = CreateCowComponent();
        var code = ComponentGenerator.Generate(comp);
        code.Should().Contain("[StructLayout(LayoutKind.Sequential, Pack = 1)]");
    }

    [Fact]
    public void Generate_ContainsStableId()
    {
        var comp = CreateCowComponent();
        var code = ComponentGenerator.Generate(comp);
        code.Should().Contain("[StableId(\"test-stable-id\")]");
    }

    [Fact]
    public void Generate_ContainsIComponent()
    {
        var comp = CreateCowComponent();
        var code = ComponentGenerator.Generate(comp);
        code.Should().Contain("public struct CowComponent : IComponent");
    }

    [Fact]
    public void Generate_ContainsFields()
    {
        var comp = CreateCowComponent();
        var code = ComponentGenerator.Generate(comp);
        code.Should().Contain("public int Exhaust;");
        code.Should().Contain("public bool IsMilking;");
        code.Should().Contain("public Entity HouseId;");
        code.Should().Contain("public Vector2 SpawnPosition;");
    }

    [Fact]
    public void Generate_MarkerComponent_HasNoFields()
    {
        var comp = new ComponentDescriptor { ComponentName = "WallComponent", StableId = "wall-id" };
        var code = ComponentGenerator.Generate(comp);
        code.Should().Contain("public struct WallComponent : IComponent");
    }

    [Fact]
    public void Generate_ContainsAutoGeneratedComment()
    {
        var comp = CreateCowComponent();
        var code = ComponentGenerator.Generate(comp);
        code.Should().StartWith("// <auto-generated/>");
    }

    [Fact]
    public void MapType_MapsAllSupportedTypes()
    {
        ComponentGenerator.MapType("int").Should().Be("int");
        ComponentGenerator.MapType("bool").Should().Be("bool");
        ComponentGenerator.MapType("Entity").Should().Be("Entity");
        ComponentGenerator.MapType("Vector2").Should().Be("Vector2");
        ComponentGenerator.MapType("string").Should().Be("FixedString32");
    }

    [Fact]
    public void MapType_PassesThroughUnknown()
    {
        ComponentGenerator.MapType("CustomType").Should().Be("CustomType");
    }

    [Fact]
    public void Generate_EnumField_PassesThroughTypeName()
    {
        var comp = new ComponentDescriptor
        {
            ComponentName = "TestComponent",
            StableId = "test-id",
            Fields = new List<FieldDescriptor>
            {
                new() { Name = "Layer", TypeName = "CollisionLayer", IsEnum = true },
            }
        };
        var code = ComponentGenerator.Generate(comp);
        code.Should().Contain("public CollisionLayer Layer;");
    }

    private static ComponentDescriptor CreateCowComponent() => new()
    {
        ComponentName = "CowComponent",
        StableId = "test-stable-id",
        Fields = new List<FieldDescriptor>
        {
            new() { Name = "Exhaust", TypeName = "int" },
            new() { Name = "MaxExhaust", TypeName = "int" },
            new() { Name = "IsMilking", TypeName = "bool" },
            new() { Name = "HouseId", TypeName = "Entity" },
            new() { Name = "SpawnPosition", TypeName = "Vector2" },
        }
    };
}
