// <auto-generated/> test file
using FluentAssertions;
using Template.CodeGen.Parsing;
using Xunit;

namespace Template.CodeGen.Tests;

public class TscnParserTests
{
    private const string CowEntityTscn = @"
[gd_scene format=3 uid=""uid://test123""]

[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkEntity.cs"" id=""1_entity""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkComponent.cs"" id=""2_comp""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkPhysicsBody.cs"" id=""3_phys""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkNavAgent.cs"" id=""4_nav""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkState.cs"" id=""5_state""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkSkin.cs"" id=""6_skin""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkVisualBinding.cs"" id=""7_bind""]
[ext_resource type=""PackedScene"" path=""res://templates/characters/Character.tscn"" id=""8_char""]

[node name=""Cow"" type=""Node3D""]
script = ExtResource(""1_entity"")
EntityName = ""Cow""
StableIdSeed = ""test-seed-cow""

[node name=""CowComponent"" type=""Node"" parent="".""]
script = ExtResource(""2_comp"")
ComponentName = ""CowComponent""
FieldNames = PackedStringArray(""Exhaust"", ""MaxExhaust"", ""IsMilking"", ""HouseId"", ""SpawnPosition"", ""FollowingPlayer"")
FieldTypes = PackedStringArray(""int"", ""int"", ""bool"", ""Entity"", ""Vector2"", ""Entity"")

[node name=""Physics"" type=""Node"" parent="".""]
script = ExtResource(""3_phys"")
BodyType = ""CharacterBody2D""
ShapeType = ""Circle""
ShapeRadius = 0.5
CollisionLayer = 1
CollisionMask = 3

[node name=""NavAgent"" type=""Node"" parent="".""]
script = ExtResource(""4_nav"")
MaxSpeed = 10
TargetDesiredDistance = 2.0
PathDesiredDistance = 1.0
Radius = 0.5

[node name=""State"" type=""Node"" parent="".""]
script = ExtResource(""5_state"")

[node name=""Skin"" type=""Node"" parent="".""]
script = ExtResource(""6_skin"")

[node name=""CapacityBinding"" type=""Node"" parent="".""]
script = ExtResource(""7_bind"")
ComponentField = ""Exhaust""
TargetNodePath = ""Capacity""
TargetProperty = ""text""

[node name=""Character"" parent=""."" instance=ExtResource(""8_char"")]
";

    private const string MinimalEntityTscn = @"
[gd_scene format=3]

[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkEntity.cs"" id=""1_e""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkComponent.cs"" id=""2_c""]

[node name=""Wall"" type=""Node3D""]
script = ExtResource(""1_e"")
EntityName = ""Wall""
StableIdSeed = ""test-seed-wall""

[node name=""WallComponent"" type=""Node"" parent="".""]
script = ExtResource(""2_c"")
ComponentName = ""WallComponent""
";

    private const string NoEntityTscn = @"
[gd_scene format=3]

[node name=""JustAScene"" type=""Node3D""]

[node name=""MeshInstance3D"" type=""MeshInstance3D"" parent="".""]
";

    private const string MetadataFieldsTscn = @"
[gd_scene format=3]

[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkEntity.cs"" id=""1_e""]
[ext_resource type=""Script"" path=""res://Scripts/Framework/FrameworkComponent.cs"" id=""2_c""]

[node name=""Coin"" type=""Node3D""]
script = ExtResource(""1_e"")
EntityName = ""Coin""
StableIdSeed = ""test-seed-coin""

[node name=""CoinComponent"" type=""Node"" parent="".""]
script = ExtResource(""2_c"")
ComponentName = ""CoinComponent""
metadata/field_Value = ""int:5""
metadata/field_IsCollected = ""bool""
";

    private readonly TscnParser _parser = new();

    [Fact]
    public void Parse_CowEntity_ExtractsEntityName()
    {
        var result = _parser.Parse(CowEntityTscn);
        result.Should().NotBeNull();
        result!.EntityName.Should().Be("Cow");
    }

    [Fact]
    public void Parse_CowEntity_ExtractsStableIdSeed()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.StableIdSeed.Should().Be("test-seed-cow");
    }

    [Fact]
    public void Parse_CowEntity_ExtractsComponent()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.Components.Should().HaveCount(1);
        result.Components[0].ComponentName.Should().Be("CowComponent");
    }

    [Fact]
    public void Parse_CowEntity_ExtractsComponentFields()
    {
        var result = _parser.Parse(CowEntityTscn);
        var fields = result!.Components[0].Fields;
        fields.Should().HaveCount(6);
        fields[0].Name.Should().Be("Exhaust");
        fields[0].TypeName.Should().Be("int");
        fields[3].Name.Should().Be("HouseId");
        fields[3].TypeName.Should().Be("Entity");
        fields[4].Name.Should().Be("SpawnPosition");
        fields[4].TypeName.Should().Be("Vector2");
    }

    [Fact]
    public void Parse_CowEntity_ExtractsPhysicsConfig()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.Physics.Should().NotBeNull();
        result.Physics!.BodyType.Should().Be(Models.PhysicsBodyType.CharacterBody2D);
        result.Physics.ShapeType.Should().Be(Models.CollisionShapeType.Circle);
        result.Physics.ShapeRadius.Should().Be(0.5f);
        result.Physics.CollisionLayer.Should().Be(1u);
        result.Physics.CollisionMask.Should().Be(3u);
    }

    [Fact]
    public void Parse_CowEntity_ExtractsNavAgent()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.NavAgent.Should().NotBeNull();
        result.NavAgent!.MaxSpeed.Should().Be(10f);
        result.NavAgent.TargetDesiredDistance.Should().Be(2.0f);
    }

    [Fact]
    public void Parse_CowEntity_DetectsState()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.HasState.Should().BeTrue();
    }

    [Fact]
    public void Parse_CowEntity_DetectsSkin()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.HasSkin.Should().BeTrue();
    }

    [Fact]
    public void Parse_CowEntity_ExtractsVisualBinding()
    {
        var result = _parser.Parse(CowEntityTscn);
        result!.VisualBindings.Should().HaveCount(1);
        result.VisualBindings[0].ComponentField.Should().Be("Exhaust");
        result.VisualBindings[0].TargetNodePath.Should().Be("Capacity");
        result.VisualBindings[0].TargetProperty.Should().Be("text");
    }

    [Fact]
    public void Parse_MinimalEntity_Works()
    {
        var result = _parser.Parse(MinimalEntityTscn);
        result.Should().NotBeNull();
        result!.EntityName.Should().Be("Wall");
        result.Components.Should().HaveCount(1);
        result.Components[0].IsMarkerComponent.Should().BeTrue();
        result.Physics.Should().BeNull();
        result.HasState.Should().BeFalse();
    }

    [Fact]
    public void Parse_NoEntity_ReturnsNull()
    {
        var result = _parser.Parse(NoEntityTscn);
        result.Should().BeNull();
    }

    [Fact]
    public void Parse_MetadataFields_ExtractsFieldsFromMetadata()
    {
        var result = _parser.Parse(MetadataFieldsTscn);
        var fields = result!.Components[0].Fields;
        fields.Should().HaveCount(2);
        fields[0].Name.Should().Be("Value");
        fields[0].TypeName.Should().Be("int");
        fields[0].DefaultValue.Should().Be("5");
        fields[1].Name.Should().Be("IsCollected");
        fields[1].TypeName.Should().Be("bool");
        fields[1].DefaultValue.Should().BeNull();
    }

    [Fact]
    public void GenerateDeterministicGuid_IsDeterministic()
    {
        var g1 = TscnParser.GenerateDeterministicGuid("seed", "name");
        var g2 = TscnParser.GenerateDeterministicGuid("seed", "name");
        g1.Should().Be(g2);
    }

    [Fact]
    public void GenerateDeterministicGuid_DifferentInputs_DifferentGuids()
    {
        var g1 = TscnParser.GenerateDeterministicGuid("seed1", "name");
        var g2 = TscnParser.GenerateDeterministicGuid("seed2", "name");
        g1.Should().NotBe(g2);
    }

    [Fact]
    public void GenerateDeterministicGuid_IsValidGuid()
    {
        var guid = TscnParser.GenerateDeterministicGuid("seed", "name");
        Guid.TryParse(guid, out _).Should().BeTrue();
    }
}
