using FluentAssertions;
using Template.CodeGen.Generators;
using Template.CodeGen.Models;
using Xunit;

namespace Template.CodeGen.Tests;

public class ViewModelGeneratorTests
{
    [Fact]
    public void Generate_ExtendsEntityViewModel()
    {
        var entity = CreateSimpleEntity("Grass");
        var code = ViewModelGenerator.Generate(entity);
        code.Should().Contain("public partial class GrassViewModel : EntityViewModel");
    }

    [Fact]
    public void Generate_CreatesDefinitionModel()
    {
        var entity = CreateSimpleEntity("Grass");
        var code = ViewModelGenerator.Generate(entity);
        code.Should().Contain("public GrassDefinitionModel Grass { get; }");
        code.Should().Contain("Grass = new GrassDefinitionModel(ReactiveSystem.Instance, context);");
        code.Should().Contain("Disposables.Add(Grass);");
    }

    [Fact]
    public void Generate_WithSkin_AddsSkinSupport()
    {
        var entity = CreateSimpleEntity("Cow");
        entity.HasSkin = true;
        var code = ViewModelGenerator.Generate(entity);
        code.Should().Contain("public SkinComponentModel Skin { get; }");
        code.Should().Contain("public ReactiveProperty<bool> IsHidden { get; }");
        code.Should().Contain("HiddenComponent");
    }

    [Fact]
    public void Generate_WithoutSkin_NoSkinProperties()
    {
        var entity = CreateSimpleEntity("Wall");
        var code = ViewModelGenerator.Generate(entity);
        code.Should().NotContain("SkinComponentModel");
        code.Should().NotContain("IsHidden");
    }

    [Fact]
    public void Generate_IsPartial_WithHooks()
    {
        var entity = CreateSimpleEntity("Grass");
        var code = ViewModelGenerator.Generate(entity);
        code.Should().Contain("public partial class GrassViewModel");
        code.Should().Contain("partial void OnCreated();");
        code.Should().Contain("partial void OnInitialize(Context context);");
    }

    [Fact]
    public void Generate_ContainsAutoGenerated()
    {
        var entity = CreateSimpleEntity("Grass");
        var code = ViewModelGenerator.Generate(entity);
        code.Should().StartWith("// <auto-generated/>");
    }

    [Fact]
    public void Generate_OnInitialize_CalledBeforeOnCreated()
    {
        var entity = CreateSimpleEntity("Grass");
        var code = ViewModelGenerator.Generate(entity);
        var initIdx = code.IndexOf("OnInitialize(context);");
        var createdIdx = code.IndexOf("OnCreated();");
        initIdx.Should().BeGreaterThan(-1);
        createdIdx.Should().BeGreaterThan(initIdx);
    }

    [Fact]
    public void Generate_OnInitialize_ReceivesContext()
    {
        var entity = CreateSimpleEntity("Grass");
        var code = ViewModelGenerator.Generate(entity);
        code.Should().Contain("OnInitialize(context);");
        code.Should().Contain("partial void OnInitialize(Context context);");
    }

    private static EntityDescriptor CreateSimpleEntity(string name) => new()
    {
        EntityName = name,
        Components = new List<ComponentDescriptor> { new() { ComponentName = $"{name}Component" } }
    };
}
