// <auto-generated/>
using Deterministic.GameFramework.ECS;
using Deterministic.GameFramework.TwoD;
using Deterministic.GameFramework.Physics2D.Components;
using Deterministic.GameFramework.Types;
using Deterministic.GameFramework.Reactive;
using Deterministic.GameFramework.DAR;
using Template.Shared.Components;
using System.Collections.Generic;

namespace Template.Shared.Definitions;

[EntityDefinition(
    typeof(Transform2D),
    typeof(MushroomCaveComponent),
    typeof(StaticBody2D),
    typeof(CollisionShape2D))]
public static partial class MushroomCaveDefinition
{
    public static Entity Create(Context ctx, Vector2 position)
    {
        var entity = ctx.CreateEntity<MushroomCaveComponent>();

        ref var component = ref ctx.GetComponent<MushroomCaveComponent>(entity);

        ctx.AddComponent(entity, new Transform2D(position, 0, Vector2.One));

        var entityBody = StaticBody2D.Default;
        entityBody.CollisionLayer = 1u;
        entityBody.CollisionMask = 1u;
        ctx.AddComponent(entity, entityBody);

        ctx.AddComponent(entity, CollisionShape2D.CreateRectangle(new Vector2(2.6890106f, 0.78665674f)));

        var childEntities = new Dictionary<string, Entity>
        {
        };
        component = ref ctx.GetComponent<MushroomCaveComponent>(entity);

        OnEntityCreated(ctx, entity, ref component, childEntities);

        return entity;
    }

    static partial void OnEntityCreated(Context ctx, Entity entity, ref MushroomCaveComponent component, Dictionary<string, Entity> childEntities);
}
